version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: M365.Api/Dockerfile
    ports:
      - "5076:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: move365-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd!
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: